### PR TITLE
Chore: file scoped namespace

### PR DESCRIPTION
**Pull request by brmassa**
Implementation of #154 

Note: External projects (submodules DotCast and Veldrid) were not affected. It will raise warnings until they are changed in their own repos

### CODE REVIEW

**Comment by michaelsakharov** [comment]
Is merging into Main intended?

**Comment by brmassa** [comment]
Well why not?

AFAIK, development branch will basically overwrite main.

If eventually there is any file from main that will not be overwritten, we can perform this change on these dozen remaining files later.

Any thoughts?

**Comment by PaperPrototype** [comment]
I think the plan was to do everything in development and once it is all cleaned up and ready just do a single merge into main

**Comment by brmassa** [comment]
@michaelsakharov ohhh now that Ive noticed that generate the Merge Request against main. My bad. It's designed to be applied to dev.

**Pull request merged**
